version: "3.9"

services:
  invoice-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invoice-service
    ports:
      - "8007:8000"
    env_file:
      - .env
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
    restart: unless-stopped
    # entrypoint: ["sleep", "1h"]